version: '3'

services:
  betehero-pgsql:
    image: "bitnami/postgresql"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=betheherodb
    volumes:
      - "pgdata:/bitnami/postgresql"
    networks:
      - container-network

  application-bethehero:
    build: .
    container_name: bethehero-api
    depends_on:
      - bethehero-pgsql
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    networks:
      - container-network

networks:
  container-network:
    driver: bridge

volumes:
  pgdata:
    driver: local